import { Archive, ArchiveRestore, ArrowLeft, CheckCheck, ChevronDown, ChevronUp, Edit3, ExternalLink, FileText, PanelsTopLeft, RefreshCw, Save, SkipForward, Sparkles, X } from 'lucide-react'
import { FormEvent, useCallback, useEffect, useMemo, useState } from 'react'
import { Background, Controls, Handle, MarkerType, MiniMap, Position, ReactFlow, useEdgesState, useNodesState, type Connection, type Edge, type Node } from '@xyflow/react'
import { Link, useParams } from 'react-router-dom'
import { api } from '../api'
import { dateInput, Empty, Field, Loading, PageHead, RiskBadge, Toast, fmtDate } from '../components'
import type { AIAnalysis, Definition, Person, Requirement, RequirementNode } from '../types'

const statuses:{value:string;label:string}[]=[{value:'not_started',label:'未开始'},{value:'in_progress',label:'进行中'},{value:'blocked',label:'受阻'},{value:'completed',label:'已完成'},{value:'skipped',label:'已跳过'}]
const statusLabel=(s:string)=>statuses.find(x=>x.value===s)?.label||s

function flowOrder(nodes:RequirementNode[],edges:{source:string;target:string}[]):RequirementNode[]{
  const byId=new Map(nodes.map(node=>[node.id,node]))
  const order=new Map(nodes.map((node,index)=>[node.id,index]))
  const next=new Map<string,string[]>()
  const degree=new Map(nodes.map(node=>[node.id,0]))
  edges.forEach(edge=>{if(!byId.has(edge.source)||!byId.has(edge.target))return;const targets=next.get(edge.source)||[];if(targets.includes(edge.target))return;targets.push(edge.target);next.set(edge.source,targets);degree.set(edge.target,(degree.get(edge.target)||0)+1)})
  const ready=nodes.filter(node=>degree.get(node.id)===0).sort((a,b)=>(order.get(a.id)||0)-(order.get(b.id)||0)).map(node=>node.id)
  const result:RequirementNode[]=[]
  while(ready.length){const id=ready.shift()!;const node=byId.get(id);if(node)result.push(node);(next.get(id)||[]).forEach(target=>{degree.set(target,(degree.get(target)||0)-1);if(degree.get(target)===0)ready.push(target)});ready.sort((a,b)=>(order.get(a)||0)-(order.get(b)||0))}
  nodes.forEach(node=>{if(!result.some(item=>item.id===node.id))result.push(node)})
  return result
}

function ScheduleNode({data}:{data:{node:RequirementNode}}){
  const n=data.node
  return <div className={`schedule-node status-${n.status} risk-${n.risk_level}`} style={{'--domain':n.domain_color} as React.CSSProperties}><Handle type="target" position={Position.Left}/><div className="node-domain">{n.domain_name}</div><strong>{n.name}</strong><span>{statusLabel(n.status)}</span>{n.risk_reasons.length>0&&<small>{n.risk_reasons[0]}</small>}<Handle type="source" position={Position.Right}/></div>
}
const nodeTypes={schedule:ScheduleNode}

export default function RequirementDetail(){
  const {id}=useParams()
  const [item,setItem]=useState<Requirement>()
  const [people,setPeople]=useState<Person[]>([])
  const [selected,setSelected]=useState<string>()
  const [message,setMessage]=useState('')
  const [error,setError]=useState('')
  const [analyzing,setAnalyzing]=useState(false)
  const [editing,setEditing]=useState(false)
  const [editingGraph,setEditingGraph]=useState(false)
  const [definitions,setDefinitions]=useState<Definition[]>([])
  const [newDefinition,setNewDefinition]=useState('')
  const [newDomain,setNewDomain]=useState('')
  const [selectedEdge,setSelectedEdge]=useState<string>()
  const load=useCallback(()=>id?api.get<Requirement>(`/requirements/${id}`).then(setItem):Promise.resolve(),[id])
  useEffect(()=>{load();api.get<Person[]>('/people').then(setPeople);api.get<Definition[]>('/node-definitions').then(setDefinitions)},[load])
  const graphNodes=useMemo<Node[]>(()=>item?.nodes?.map(n=>({id:n.id,type:'schedule',position:n.position,data:{node:n}}))||[],[item])
  const graphEdges=useMemo<Edge[]>(()=>item?.edges?.map(e=>({id:e.id,source:e.source,target:e.target,markerEnd:{type:MarkerType.ArrowClosed},animated:true,style:{stroke:'#8fa097'}}))||[],[item])
  const [nodes,setNodes,onNodesChange]=useNodesState(graphNodes)
  const [edges,setEdges,onEdgesChange]=useEdgesState(graphEdges)
  const [domainFilter,setDomainFilter]=useState('all')
  const [checkedNodeIds,setCheckedNodeIds]=useState<string[]>([])
  const [batchOwnerIds,setBatchOwnerIds]=useState<string[]>([])
  const [batchOwnerMode,setBatchOwnerMode]=useState<'replace'|'append'>('replace')
  useEffect(()=>setNodes(graphNodes),[graphNodes,setNodes])
  useEffect(()=>setEdges(graphEdges),[graphEdges,setEdges])
  if(!item)return <Loading/>
  const requirementId=item.id
  const graphNodeCount=item.nodes?.length||0
  const selectedNode=item.nodes?.find(n=>n.id===selected)
  const orderedNodes=flowOrder(item.nodes||[],item.edges||[])
  const domains=[...new Map((item.nodes||[]).map(node=>[node.domain_name,node.domain_color])).entries()]
  const visibleNodes=orderedNodes.filter(node=>domainFilter==='all'||node.domain_name===domainFilter)
  const visibleNodeIds=visibleNodes.map(node=>node.id)
  const allVisibleChecked=visibleNodes.length>0&&visibleNodes.every(node=>checkedNodeIds.includes(node.id))
  async function saveNode(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(!selectedNode)return;const fd=new FormData(e.currentTarget);const body={planned_start:fd.get('planned_start')||null,planned_end:fd.get('planned_end')||null,status:fd.get('status'),notes:fd.get('notes'),blocked_reason:fd.get('blocked_reason'),owner_ids:fd.getAll('owner_ids').map(String)};try{await api.patch(`/requirement-nodes/${selectedNode.id}`,body);setMessage('节点计划已保存，AI 结论已标记为待更新');setError('');load()}catch(err){setError((err as Error).message)}}
  async function moveNode(node:Node){try{await api.patch(`/requirement-nodes/${node.id}`,{position_x:node.position.x,position_y:node.position.y});setItem(current=>current?{...current,nodes:current.nodes?.map(item=>item.id===node.id?{...item,position:{x:node.position.x,y:node.position.y}}:item)}:current)}catch(err){setError((err as Error).message)}}
  async function connectNodes(connection:Connection){if(!editingGraph||!connection.source||!connection.target)return;try{await api.post(`/requirements/${requirementId}/edges`,{source:connection.source,target:connection.target});setMessage('节点流向已保存');setError('');await load()}catch(err){setError((err as Error).message)}}
  async function addNode(){const definition=definitions.find(item=>item.id===newDefinition);if(!definition)return;const domainId=newDomain||(definition.domains?.[0]?.id||definition.domain.id);try{await api.post(`/requirements/${requirementId}/nodes`,{definition_id:definition.id,domain_id:domainId,position_x:120+(graphNodeCount%3)*260,position_y:100+Math.floor(graphNodeCount/3)*170});setNewDefinition('');setNewDomain('');setMessage('交付节点已添加');setError('');await load()}catch(err){setError((err as Error).message)}}
  async function deleteSelectedGraphItem(){if(selectedEdge){try{await api.del(`/requirement-edges/${selectedEdge}`);setSelectedEdge(undefined);setMessage('节点流向已删除');await load()}catch(err){setError((err as Error).message)}return}if(!selected||!window.confirm('确定删除当前节点吗？节点计划和相关连线也会被删除。'))return;try{await api.del(`/requirement-nodes/${selected}`);setSelected(undefined);setMessage('交付节点已删除');setError('');await load()}catch(err){setError((err as Error).message)}}
  function toggleNodeChecked(nodeId:string){setCheckedNodeIds(current=>current.includes(nodeId)?current.filter(id=>id!==nodeId):[...current,nodeId])}
  function toggleVisibleChecked(){setCheckedNodeIds(current=>allVisibleChecked?current.filter(id=>!visibleNodeIds.includes(id)):[...new Set([...current,...visibleNodeIds])])}
  async function batchStatus(status:string){if(!checkedNodeIds.length)return;try{await api.post('/requirement-nodes/batch-status',{node_ids:checkedNodeIds,status});setCheckedNodeIds([]);setMessage(`已批量${status==='completed'?'完成':status==='skipped'?'跳过':'更新'} ${checkedNodeIds.length} 个节点`);setError('');await load()}catch(err){setError((err as Error).message)}}
  async function batchOwners(){if(!checkedNodeIds.length)return;try{const count=checkedNodeIds.length;await api.post('/requirement-nodes/batch-owners',{node_ids:checkedNodeIds,owner_ids:batchOwnerIds,mode:batchOwnerMode});setCheckedNodeIds([]);setBatchOwnerIds([]);setMessage(`已为 ${count} 个节点${batchOwnerMode==='replace'?'覆盖':'追加'}负责人`);setError('');await load()}catch(err){setError((err as Error).message)}}
  async function saveRequirement(e:FormEvent<HTMLFormElement>){e.preventDefault();const fd=new FormData(e.currentTarget);const body={name:String(fd.get('name')||'').trim(),owner_id:String(fd.get('owner_id')||''),target_version:String(fd.get('target_version')||''),notes:String(fd.get('notes')||''),meego_url:String(fd.get('meego_url')||'').trim()||null,requirement_url:String(fd.get('requirement_url')||'').trim()||null,figma_url:String(fd.get('figma_url')||'').trim()||null};try{const result=await api.patch<Requirement>(`/requirements/${requirementId}`,body);setItem(result);setEditing(false);setMessage('需求信息已保存');setError('')}catch(err){setError((err as Error).message)}}
  async function toggleArchive(){const current=item;if(!current)return;const archived=!current.archived;const action=archived?'归档':'取消归档';if(archived&&!window.confirm(`确定归档需求「${current.name}」吗？归档后将不再参与风险刷新和通知。`))return;try{const result=await api.patch<Requirement>(`/requirements/${requirementId}`,{archived});setItem(result);setMessage(`需求已${action}`);setError('')}catch(err){setError((err as Error).message)}}
  async function analyze(){setAnalyzing(true);setError('');try{const result=await api.post<Requirement>(`/requirements/${requirementId}/ai-analysis`,{});setItem(result);setMessage('AI 风险分析已更新')}catch(err){setError((err as Error).message)}finally{setAnalyzing(false)}}
  return <>
    <PageHead eyebrow={`需求 #${item.sequence_id}${item.archived?' · 已归档':''}`} title={item.name} description={`${item.owner.display_name} · ${item.template_name} · ${item.target_version||'未设置版本'}`} action={<div className="detail-actions"><Link className="button ghost" to="/requirements"><ArrowLeft size={16}/>返回需求</Link><button className="button ghost" onClick={()=>setEditing(!editing)}>{editing?<X size={16}/>:<Edit3 size={16}/>} {editing?'取消编辑':'编辑需求'}</button><button className="button ghost" onClick={toggleArchive}>{item.archived?<ArchiveRestore size={16}/>:<Archive size={16}/>} {item.archived?'取消归档':'归档需求'}</button></div>}/>
    {editing&&<form className="panel requirement-edit-form" onSubmit={saveRequirement}><div className="section-head"><div><h2>编辑需求信息</h2><p>修改基础信息不会改变已经生成的交付节点。</p></div></div><div className="form-grid"><Field label="需求名称"><input name="name" required defaultValue={item.name}/></Field><Field label="需求负责人"><select name="owner_id" required defaultValue={item.owner_id}><option value="" disabled>选择负责人</option>{people.filter(person=>person.active||person.id===item.owner_id).map(person=><option value={person.id} key={person.id}>{person.display_name} · {person.role_name}</option>)}</select></Field><Field label="目标版本"><input name="target_version" defaultValue={item.target_version||''}/></Field><Field label="说明"><textarea name="notes" rows={3} defaultValue={item.notes||''}/></Field><Field label="Meego 地址"><input name="meego_url" type="url" defaultValue={item.meego_url||''}/></Field><Field label="需求文档地址"><input name="requirement_url" type="url" defaultValue={item.requirement_url||''}/></Field><Field label="Figma 地址"><input name="figma_url" type="url" defaultValue={item.figma_url||''}/></Field></div><div className="form-actions"><button type="button" className="button ghost" onClick={()=>setEditing(false)}>取消</button><button className="button primary"><Save size={16}/>保存需求</button></div></form>}
    <div className="detail-summary panel"><div><small>整体风险</small><RiskBadge level={item.risk_level}/></div><div><small>交付进度</small><strong>{item.completed_nodes}/{item.total_nodes} 节点</strong></div><div><small>当前节点</small><strong>{item.current_nodes.join('、')||'已完成'}</strong></div><div><small>计划完成</small><strong>{fmtDate(item.planned_completion)}</strong></div></div>
    {(item.meego_url||item.requirement_url||item.figma_url)&&<div className="resource-links">{item.meego_url&&<a href={item.meego_url} target="_blank" rel="noreferrer"><PanelsTopLeft/>Meego<ExternalLink/></a>}{item.requirement_url&&<a href={item.requirement_url} target="_blank" rel="noreferrer"><FileText/>需求文档<ExternalLink/></a>}{item.figma_url&&<a href={item.figma_url} target="_blank" rel="noreferrer"><span className="figma-mark">F</span>Figma<ExternalLink/></a>}</div>}
    {item.risk_reasons.length>0&&<div className={`risk-callout risk-${item.schedule_risk_level}`}><strong>计划风险提示</strong>{item.risk_reasons.map((r,i)=><span key={i}>· {r}</span>)}</div>}
    <AIAnalysisCard analysis={item.ai_analysis} analyzedAt={item.ai_analyzed_at} stale={item.ai_stale} error={item.ai_error} analyzing={analyzing} onAnalyze={analyze}/>
    <section className="panel flow-section"><div className="section-head"><div><h2>交付节点全景</h2><p>{editingGraph?'可拖动节点、从手柄连线；点击连线后可删除。':'节点自动跟随需求；串行与并行关系来自创建时使用的模板。'}</p></div><div className="section-actions"><button className="button ghost compact" onClick={()=>setEditingGraph(!editingGraph)}>{editingGraph?<X size={15}/>:<Edit3 size={15}/>} {editingGraph?'完成流程编辑':'编辑流程'}</button>{editingGraph&&<button className="button danger compact" onClick={deleteSelectedGraphItem} disabled={!selected&&!selectedEdge}>删除所选</button>}</div></div>{editingGraph&&<div className="flow-editor-toolbar"><select value={newDefinition} onChange={e=>{setNewDefinition(e.currentTarget.value);setNewDomain('')}}><option value="">选择要添加的节点</option>{definitions.filter(definition=>definition.active).map(definition=><option value={definition.id} key={definition.id}>{definition.name}</option>)}</select>{newDefinition&&<select value={newDomain} onChange={e=>setNewDomain(e.currentTarget.value)}><option value="">选择领域</option>{(definitions.find(definition=>definition.id===newDefinition)?.domains||[definitions.find(definition=>definition.id===newDefinition)?.domain].filter(Boolean) as Definition['domains']).map(domain=><option value={domain.id} key={domain.id}>{domain.name}</option>)}</select>}<button className="button primary compact" onClick={addNode} disabled={!newDefinition}>添加节点</button></div>}<div className="flow-canvas requirement-flow"><ReactFlow nodes={nodes} edges={edges} nodeTypes={nodeTypes} onNodesChange={onNodesChange} onEdgesChange={onEdgesChange} fitView minZoom={.45} maxZoom={1.5} nodesDraggable={editingGraph} onNodeClick={(_,n)=>{setSelected(n.id);setSelectedEdge(undefined)}} onEdgeClick={(_,edge)=>{if(editingGraph)setSelectedEdge(edge.id)}} onConnect={connectNodes} onNodeDragStop={(_,node)=>{if(editingGraph)void moveNode(node)}}><Background gap={22} size={1}/><Controls/><MiniMap nodeColor={n=>(n.data.node as RequirementNode).domain_color}/></ReactFlow></div></section>
    <section className="panel"><div className="section-head"><div><h2>节点计划与状态</h2><p>按流程流向展示；可按域筛选，并批量更新节点状态。</p></div><div className="node-table-actions"><select value={domainFilter} onChange={e=>setDomainFilter(e.currentTarget.value)}><option value="all">全部域</option>{domains.map(([name,color])=><option value={name} key={name}>{name}</option>)}</select><button type="button" className="button ghost compact" onClick={toggleVisibleChecked}>{allVisibleChecked?'取消全选':'全选当前域'}</button><button type="button" className="button ghost compact" onClick={()=>setCheckedNodeIds([])} disabled={!checkedNodeIds.length}>清空选择</button></div></div>{checkedNodeIds.length>0&&<div className="batch-status-bar"><span>已选 {checkedNodeIds.length} 个节点</span><select aria-label="批量负责人处理方式" value={batchOwnerMode} onChange={e=>setBatchOwnerMode(e.currentTarget.value as 'replace'|'append')}><option value="replace">覆盖负责人</option><option value="append">追加负责人</option></select><BatchOwnerPicker people={people} selectedIds={batchOwnerIds} onChange={setBatchOwnerIds}/><button type="button" className="button primary compact" onClick={batchOwners} disabled={batchOwnerMode==='append'&&batchOwnerIds.length===0}>批量设置负责人</button><button type="button" className="button primary compact" onClick={()=>batchStatus('completed')}><CheckCheck size={15}/>批量完成</button><button type="button" className="button ghost compact" onClick={()=>batchStatus('skipped')}><SkipForward size={15}/>批量跳过</button></div>}<div className="node-table"><div className="node-table-head"><span>选择</span><span>节点</span><span>负责人</span><span>预期开始</span><span>预期结束</span><span>状态</span><span>风险</span><span/></div>{visibleNodes.map(n=><div key={n.id} className={selected===n.id?'node-table-wrap selected':'node-table-wrap'}><div className="node-row" onClick={()=>setSelected(selected===n.id?undefined:n.id)}><label className="node-select" onClick={e=>e.stopPropagation()}><input type="checkbox" checked={checkedNodeIds.includes(n.id)} onChange={()=>toggleNodeChecked(n.id)}/></label><span><i style={{background:n.domain_color}}/>{n.name}<small>{n.domain_name}</small></span><span>{n.owners.map(x=>x.display_name).join('、')||'未设置'}</span><span>{fmtDate(n.planned_start)}</span><span>{fmtDate(n.planned_end)}</span><span><b className={`status-pill ${n.status}`}>{statusLabel(n.status)}</b></span><span><RiskBadge level={n.risk_level}/></span><span>{selected===n.id?<ChevronUp/>:<ChevronDown/>}</span></div>{selected===n.id&&<NodeEditor node={n} people={people} onSave={saveNode}/>}</div>)}</div></section>
    {!item.nodes?.length&&<Empty title="没有交付节点" detail="当前需求未生成节点。"/>}{message&&<Toast text={message}/>} {error&&<Toast text={error} type="error"/>}
  </>
}

function AIAnalysisCard({analysis,analyzedAt,stale,error,analyzing,onAnalyze}:{analysis?:AIAnalysis;analyzedAt?:string;stale:boolean;error?:string;analyzing:boolean;onAnalyze:()=>void}){
  return <section className="panel ai-result-card"><div className="ai-result-head"><div><Sparkles/><span><strong>AI 综合风险分析</strong><small>{analysis?`${fmtDate(analyzedAt,true)}${stale?' · 需求已变化，建议重新分析':''}`:'尚未生成 AI 结论'}</small></span></div><button className="button ghost compact" onClick={onAnalyze} disabled={analyzing}>{analyzing?<RefreshCw className="spin"/>:<Sparkles/>}{analyzing?'分析中…':analysis?'重新分析':'立即分析'}</button></div>{analysis?<div className="ai-result-body"><div className={`ai-summary ai-${analysis.risk_level}`}><strong>{analysis.summary}</strong><span>置信度 {Math.round(analysis.confidence*100)}% · {analysis.delivery_forecast.reason}</span></div>{analysis.signals.length>0&&<div className="ai-result-section"><h4>风险信号</h4>{analysis.signals.map((signal,index)=><div className="ai-signal" key={`${signal.node_id}-${index}`}><b className={`ai-dot ${signal.risk_level}`}/><span><strong>{signal.node_name}</strong><small>{signal.reason}</small>{signal.evidence.length>0&&<em>{signal.evidence.join('；')}</em>}</span></div>)}</div>}{analysis.actions.length>0&&<div className="ai-result-section"><h4>建议动作</h4>{analysis.actions.map((action,index)=><div className="ai-action" key={index}><b>{action.priority==='high'?'高':action.priority==='medium'?'中':'低'}</b><span>{action.action}<small>{action.owner_hint}</small></span></div>)}</div>}{analysis.missing_information.length>0&&<p className="ai-missing">待补充：{analysis.missing_information.join('、')}</p>}</div>:<div className="ai-empty">开启 AI 配置后，可综合分析节点备注、排期、状态、人员和依赖信息。</div>}{error&&<div className="ai-inline-error">上次分析失败：{error}</div>}</section>
}

function NodeEditor({node,people,onSave}:{node:RequirementNode;people:Person[];onSave:(e:React.FormEvent<HTMLFormElement>)=>void}){
  return <form className="node-editor" onSubmit={onSave}><Field label="预期开始"><input type="datetime-local" name="planned_start" defaultValue={dateInput(node.planned_start)}/></Field><Field label="预期结束"><input type="datetime-local" name="planned_end" defaultValue={dateInput(node.planned_end)}/></Field><Field label="状态"><select name="status" defaultValue={node.status}>{statuses.map(s=><option value={s.value} key={s.value}>{s.label}</option>)}</select></Field><Field label="节点负责人"><div className="owner-checkboxes">{people.filter(person=>person.active).map(person=><label key={person.id}><input type="checkbox" name="owner_ids" value={person.id} defaultChecked={node.owners.some(owner=>owner.id===person.id)}/>{person.display_name} · {person.role_name}</label>)}</div></Field><Field label="受阻原因"><input name="blocked_reason" defaultValue={node.blocked_reason||''} placeholder="仅状态为受阻时填写"/></Field><Field label="节点备注"><input name="notes" defaultValue={node.notes||''}/></Field><div className="node-editor-action"><button className="button primary compact"><Save size={15}/>保存节点</button></div></form>
}

function BatchOwnerPicker({people,selectedIds,onChange}:{people:Person[];selectedIds:string[];onChange:(ids:string[])=>void}){
  const activePeople=people.filter(person=>person.active)
  return <div className="batch-owner-picker" aria-label="批量负责人"><span>负责人（可多选）</span><div>{activePeople.map(person=><label key={person.id}><input type="checkbox" checked={selectedIds.includes(person.id)} onChange={event=>onChange(event.currentTarget.checked?[...selectedIds,person.id]:selectedIds.filter(id=>id!==person.id))}/>{person.display_name} · {person.role_name}</label>)}</div></div>
}
